### ISSUE TITLE
Parallelization of infer_syntenet

### ISSUE THREAD

**Issue by dmacguigan** [almeidasilvaf/syntenet#16]
Is it possible to parallelize the `infer_syntenet` function? It seems like one could split up the pairwise calculations of collinear blocks. I'm running a dataset with ~150 taxa, guessing it will take several days to complete as a single threaded process.

**Comment by almeidasilvaf** [comment]
Hi, @dmacguigan 

That's a great suggestion, thanks! I will add an option to parallelize synteny detection asap and let you know. 

Best,
Fabricio

**Comment by almeidasilvaf** [comment]
Implemented in v1.3.3. Functions `intraspecies_synteny()`, `interspecies_synteny()`, and `infer_syntenet()` can now be parallelized by specifying a multi-core [BiocParallel](https://bioconductor.org/packages/BiocParallel) back-end to the `bp_param` parameter. 

For example, to use 8 cores on Linux and macOS, use `BiocParallel::MulticoreParam(workers = 8)`. See the vignette of BiocParallel for details.
