### ISSUE TITLE
Error in check_ngenes(seq, annotation) 

### ISSUE THREAD

**Issue by sujee119** [almeidasilvaf/syntenet#21]
Hello Fabricio,

I am running syntenet for 4 species for a project. I filtered the fasta and gff3 files to match each other using custom python scripts to match the gff3 and fasta files and checked it with custom codes. 

$ python count.py
Number of genes in athm.fasta: 27622
Number of genes in osam.fasta: 35489
Number of genes in crem.fasta: 19228
Number of genes in ppam.fasta: 22827

$ python entries.py
Number of 'gene_id' entries in athm.gff3: 27622
Number of 'gene_id' entries in osam.gff3: 35489
Number of 'gene_id' entries in crem.gff3: 19228
Number of 'gene_id' entries in ppam.gff3: 22827

however, the fuction check_input() is giving off error.

> library(syntenet)
> seqs=fasta2AAStringSetlist("fasta")
anns=gff2GRangesList("annotation")
> check_input(seqs, anns)
Error in check_ngenes(seq, annotation) :
  Number of sequences in greater than the number of genes for:
1. crem
2. osam
3. ppam

can you please assist this error?

-Sujeevan

**Comment by almeidasilvaf** [comment]
Hi, @sujee119 

Could you please show what the objects `seqs` and `anns` look like? Your session information would also help. You can run:

```r
# Summary of the objects
names(seqs)
names(anns)

lengths(seqs)
lengths(anns)

head(seqs[[1]])
head(anns[[1]])

# Session info
sessionInfo()
```

Best,
Fabricio

**Comment by sujee119** [comment]
Hello Fabricio,

Thank you for your reply. I was able to find and fix the problem. The gff3 files were too messy. I managed to fix it. 

Thank you
