### ISSUE TITLE
[BUG] Possible bug with find_GS_clusters

### ISSUE THREAD

**Issue by dmacguigan** [almeidasilvaf/syntenet#22]
I have been using the [`find_GS_clusters`](https://almeidasilvaf.github.io/syntenet/reference/find_GS_clusters.html) function to count the number of synteny clusters for several clades. However, I have noticed that when I specify `min_percentage = 100`, no clusters are returned.

On line 166 of [05_phylogenomic_profiling.R](https://github.com/almeidasilvaf/syntenet/blob/52f69617ac94ce484da9db90b6ea067f111f0a4a/R/05_phylogenomic_profiling.R#L106), you perform filtering as follows.

```
fgroup_count <- group_count[group_count$perc > min_percentage, ]
```

Should this line actually be `>=` instead of `>`? If `min_percentage = 100`, I believe this will return 0 matches.

**Comment by almeidasilvaf** [comment]
Hi, @dmacguigan 

Thank you for reporting this.

You're right, I didn't specify in the function docs if the minimum includes the value, and I agree that it's more natural to think that the minimum value is included. I just pushed a fix to this.

Best,
Fabricio

**Comment by dmacguigan** [comment]
Thanks @almeidasilvaf!
