### ISSUE TITLE
Meaning of different node size in the network plot?

### ISSUE THREAD

**Issue by YingChen94** [almeidasilvaf/syntenet#23]
Hello, thanks for the great tool! I wonder why some nodes are smaller in size (e.g. red arrows in the plot) in the network plot? Is there a particular meaning of the difference? 

<img width="347" alt="Screenshot" src="https://github.com/user-attachments/assets/3a952e5d-8571-4b97-af0b-258f25d801b0">

**Comment by almeidasilvaf** [comment]
Hi, @YingChen94 

Thank you for using __syntenet__.

The size aesthetic of nodes is mapped to node degrees (number of connections). Thus, nodes that have few connections will be smaller, while nodes with more connections will be larger.

**Comment by YingChen94** [comment]
This is helpful! Thank you for your quick reply!
