### ISSUE TITLE
Cannot reproduce the document in “syntenet as a synteny detection tool”

### ISSUE THREAD

**Issue by WWz33** [almeidasilvaf/syntenet#25]
Hi! Fabricio

Thank you very much for your reply to my last issue.
I'm not quite sure if this example file really has no results, or if it's due to a bug with the `function`

```R
library(syntenet)
fasta_dir <- system.file("extdata", "sequences", package = "syntenet")
fasta_dir
#> [1] "/home/sj/R/x86_64-pc-linux-gnu-library/4.4/syntenet/extdata/sequences"

dir(fasta_dir) # see the contents of the directory
#> [1] "Olucimarinus.fa.gz" "OspRCC809.fa.gz"
```

# Read all FASTA files in `fasta_dir`

```R
aastringsetlist <- fasta2AAStringSetlist(fasta_dir)
gff_dir <- system.file("extdata", "annotation", package = "syntenet")
gff_dir
#> [1] "/home/sj/R/x86_64-pc-linux-gnu-library/4.4/syntenet/extdata/annotation"

dir(gff_dir) # see the contents of the directory
#> [1] "Olucimarinus.gff3.gz" "OspRCC809.gff3.gz"
```

# Read all FASTA files in `fasta_dir`

```R
grangeslist <- gff2GRangesList(gff_dir)
pdata <- process_input(aastringsetlist, grangeslist)
pdata$annotation
```

> $Olucimarinus
> GRanges object with 100 ranges and 1 metadata column:
>   seqnames        ranges strand |           gene
> <Rle>     <IRanges>  <Rle> |    <character>
>   [1] Olu_Chr_1      939-3671      - | Olu_OL01G00010
> [2] Olu_Chr_1     3907-6927      + | Olu_OL01G00020
> [3] Olu_Chr_1     7085-9160      + | Olu_OL01G00030
> [4] Olu_Chr_1    9830-11480      + | Olu_OL01G00040
> [5] Olu_Chr_1   11467-12599      - | Olu_OL01G00050
> ...       ...           ...    ... .            ...
> [96] Olu_Chr_1 170975-172402      + | Olu_OL01G00960
> [97] Olu_Chr_1 172445-174757      - | Olu_OL01G00970
> [98] Olu_Chr_1 175358-176839      + | Olu_OL01G00980
> [99] Olu_Chr_1 176901-177692      - | Olu_OL01G00990

> [100] Olu_Chr_1 177742-179436      - | Olu_OL01G01000

>   seqinfo: 1 sequence from an unspecified genome; no seqlengths

> $OspRCC809
> GRanges object with 100 ranges and 1 metadata column:
>   seqnames        ranges strand |                 gene
> <Rle>     <IRanges>  <Rle> |          <character>
>   [1] Osp_chr_1      321-1142      - | Osp_ORCC809_01G00010
> [2] Osp_chr_1     1463-2089      + | Osp_ORCC809_01G00020
> [3] Osp_chr_1     2162-3370      - | Osp_ORCC809_01G00030
> [4] Osp_chr_1     3774-4424      - | Osp_ORCC809_01G00040
> [5] Osp_chr_1     4693-9924      - | Osp_ORCC809_01G00050
> ...       ...           ...    ... .                  ...
> [96] Osp_chr_1 165459-166529      - | Osp_ORCC809_01G00960
> [97] Osp_chr_1 166654-167213      - | Osp_ORCC809_01G00970
> [98] Osp_chr_1 167296-167550      + | Osp_ORCC809_01G00980
> [99] Osp_chr_1 167542-168228      + | Osp_ORCC809_01G00990

> [100] Osp_chr_1 168639-168947      - | Osp_ORCC809_01G01000

>   seqinfo: 1 sequence from an unspecified genome; no seqlengths

```
str(pdata$seq)
```

> List of 2
> $ Olucimarinus:Formal class 'AAStringSet' [package "Biostrings"] with 5 slots
> .. ..@ pool           :Formal class 'SharedRaw_Pool' [package "XVector"] with 2 slots
> .. .. .. ..@ xp_list                    :List of 1
> .. .. .. .. ..$ :<externalptr>
>   .. .. .. ..@ .link_to_cached_object_list:List of 1
> .. .. .. .. ..$ :<environment: 0x55d0e8123b58>
>   .. ..@ ranges         :Formal class 'GroupedIRanges' [package "XVector"] with 7 slots
> .. .. .. ..@ group          : int [1:100] 1 1 1 1 1 1 1 1 1 1 ...
> .. .. .. ..@ start          : int [1:100] 1 912 1701 2319 2866 3185 3547 4054 4129 4530 ...
> .. .. .. ..@ width          : int [1:100] 910 788 617 546 318 361 506 74 400 170 ...
> .. .. .. ..@ NAMES          : chr [1:100] "Olu_OL01G00010" "Olu_OL01G00020" "Olu_OL01G00030" "Olu_OL01G00040" ...
> .. .. .. ..@ elementType    : chr "ANY"
> .. .. .. ..@ elementMetadata: NULL
> .. .. .. ..@ metadata       : list()
> .. ..@ elementType    : chr "AAString"
> .. ..@ elementMetadata: NULL
> .. ..@ metadata       : list()
> $ OspRCC809   :Formal class 'AAStringSet' [package "Biostrings"] with 5 slots
> .. ..@ pool           :Formal class 'SharedRaw_Pool' [package "XVector"] with 2 slots
> .. .. .. ..@ xp_list                    :List of 1
> .. .. .. .. ..$ :<externalptr>
>   .. .. .. ..@ .link_to_cached_object_list:List of 1
> .. .. .. .. ..$ :<environment: 0x55d0e8123b58>
>   .. ..@ ranges         :Formal class 'GroupedIRanges' [package "XVector"] with 7 slots
> .. .. .. ..@ group          : int [1:100] 1 1 1 1 1 1 1 1 1 1 ...
> .. .. .. ..@ start          : int [1:100] 1 275 450 853 1070 2761 3377 3710 4260 4537 ...
> .. .. .. ..@ width          : int [1:100] 273 174 402 216 1690 615 332 549 276 202 ...
> .. .. .. ..@ NAMES          : chr [1:100] "Osp_ORCC809_01G00010" "Osp_ORCC809_01G00020" "Osp_ORCC809_01G00030" "Osp_ORCC809_01G00040" ...
> .. .. .. ..@ elementType    : chr "ANY"
> .. .. .. ..@ elementMetadata: NULL
> .. .. .. ..@ metadata       : list()
> .. ..@ elementType    : chr "AAString"
> .. ..@ elementMetadata: NULL
> .. ..@ metadata       : list()

```
data(blast_list)

names(blast_list)
#> [1] "Olucimarinus_Olucimarinus" "Olucimarinus_OspRCC809"   
#> [3] "OspRCC809_Olucimarinus"    "OspRCC809_OspRCC809"
diamond_inter <- blast_list[c(2, 3)]

str(diamond_inter)
```

> List of 2
> $ Olucimarinus_OspRCC809:'data.frame':	1261 obs. of  12 variables:
>   ..$ query        : chr [1:1261] "Olu_OL01G00080" "Olu_OL01G00090" "Olu_OL01G00100" "Olu_OL01G00110" ...
> ..$ db           : chr [1:1261] "Osp_ORCC809_01G06460" "Osp_ORCC809_01G06470" "Osp_ORCC809_01G06480" "Osp_ORCC809_01G06490" ...
> ..$ perc_identity: num [1:1261] 78.4 73.3 74.4 86.6 86 93.5 95.2 91.1 72.5 93.9 ...
> ..$ length       : int [1:1261] 37 378 156 359 549 836 227 384 418 228 ...
> ..$ mismatches   : int [1:1261] 8 94 36 45 77 35 11 34 94 14 ...
> ..$ gap_open     : int [1:1261] 0 3 1 2 0 1 0 0 4 0 ...
> ..$ qstart       : int [1:1261] 10 29 1 1 1 1 1 100 2 1 ...
> ..$ qend         : int [1:1261] 46 399 156 356 549 817 227 483 400 228 ...
> ..$ tstart       : int [1:1261] 17 68 1 8 1 1 777 1 12 9 ...
> ..$ tend         : int [1:1261] 53 445 152 366 549 836 1003 384 427 236 ...
> ..$ evalue       : num [1:1261] 1.09e-17 4.21e-176 2.05e-81 2.20e-219 0.00 ...
> ..$ bitscore     : num [1:1261] 66.2 494 234 603 977 ...
> $ OspRCC809_Olucimarinus:'data.frame':	1263 obs. of  12 variables:
>   ..$ query        : chr [1:1263] "Osp_ORCC809_01G00010" "Osp_ORCC809_01G00020" "Osp_ORCC809_01G00030" "Osp_ORCC809_01G00050" ...
> ..$ db           : chr [1:1263] "Olu_OL01G06730" "Olu_OL01G06830" "Olu_OL01G06820" "Olu_OL01G06850" ...
> ..$ perc_identity: num [1:1263] 52.2 58.5 71.5 66.3 60 85.2 84.1 84.7 73.1 82.7 ...
> ..$ length       : int [1:1263] 226 176 375 255 623 324 546 274 197 168 ...
> ..$ mismatches   : int [1:1263] 102 63 104 85 219 47 82 41 53 28 ...
> ..$ gap_open     : int [1:1263] 4 5 2 1 6 1 2 1 0 1 ...
> ..$ qstart       : int [1:1263] 32 1 30 1078 6 9 2 1 1 1 ...
> ..$ qend         : int [1:1263] 256 168 402 1331 601 332 542 274 197 167 ...
> ..$ tstart       : int [1:1263] 1 1 91 1 6 7 6 60 1 48 ...
> ..$ tend         : int [1:1263] 221 174 464 255 625 329 551 332 197 215 ...
> ..$ evalue       : num [1:1263] 5.96e-70 8.49e-51 7.22e-191 8.74e-108 5.89e-256 ...
> ..$ bitscore     : num [1:1263] 212 157 533 340 713 560 868 484 295 296 ...

# Double-check if we have processed annotation for these 2 species

```R
names(pdata$annotation)
#> [1] "Olucimarinus" "OspRCC809"
```

# Detect interspecies synteny

```R
intersyn <- interspecies_synteny(diamond_inter, pdata$annotation)

intersyn # see where the .collinearity file is
#> [1] "/tmp/RtmpDP0HhR/inter/Olucimarinus_OspRCC809.collinearity"
```

# Read .collinearity file

```R
ostreoccocus_syn <- parse_collinearity(intersyn)

system("cat /tmp/RtmpDP0HhR/inter/Olucimarinus_OspRCC809.collinearity")
############## Parameters ###############
MATCH_SCORE: 50
GAP_PENALTY: -1
MATCH_SIZE: 5
OVERLAP_WINDOW: 5
E_VALUE: 1e-05
MAX GAPS: 25
IS_PAIRWISE: 1
IN_SYNTENY: 2
############## Statistics ###############
Number of collinear genes: 0, Percentage: 0.00
Number of all genes: 200
#########################################

ostreoccocus_syn
#> [1] NULL
```

# [[example](https://almeidasilvaf.github.io/syntenet/reference/interspecies_synteny.html)](https://almeidasilvaf.github.io/syntenet/reference/interspecies_synteny.html)

```R
# Load data

data(proteomes)
data(blast_list)
data(annotation)

# Get DIAMOND and processed annotation lists

blast_inter <- blast_list[2]
annotation <- process_input(proteomes, annotation)$annotation

# Detect interspecies synteny

intersyn <- interspecies_synteny(blast_inter, annotation)

intersyn
#> [1] "/tmp/RtmpDP0HhR/inter/Olucimarinus_OspRCC809.collinearity"
system("head -n20 /tmp/RtmpDP0HhR/inter/Olucimarinus_OspRCC809.collinearity")
```

> ```
> ############### Parameters ###############
> # MATCH_SCORE: 50
> # GAP_PENALTY: -1
> # MATCH_SIZE: 5
> # OVERLAP_WINDOW: 5
> # E_VALUE: 1e-05
> # MAX GAPS: 25
> # IS_PAIRWISE: 1
> # IN_SYNTENY: 2
> ############### Statistics ###############
> # Number of collinear genes: 2124, Percentage: 63.67
> # Number of all genes: 3336
> ##########################################
> ## Alignment 0: score=27132.0 e_value=0 N=546 Olu_Chr_1&Osp_chr_1 minus
>   0-  0:	Olu_OL01G00100	Osp_ORCC809_01G06480	  2e-81
>   0-  1:	Olu_OL01G00130	Osp_ORCC809_01G06440	      0
>   0-  2:	Olu_OL01G00150	Osp_ORCC809_01G06420	 3e-258
>   0-  3:	Olu_OL01G00160	Osp_ORCC809_01G06410	 4e-214
>   0-  4:	Olu_OL01G00170	Osp_ORCC809_01G06400	 3e-161
>   0-  5:	Olu_OL01G00180	Osp_ORCC809_01G06390	 4e-190
> ```

```R
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Linux Mint 21.1

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] syntenet_1.9.1      Biostrings_2.72.1   GenomeInfoDb_1.40.1 XVector_0.44.0      IRanges_2.38.1      S4Vectors_0.42.1   
[7] BiocGenerics_0.50.0

loaded via a namespace (and not attached):
 [1] SummarizedExperiment_1.34.0 gtable_0.3.6                rjson_0.2.23                xfun_0.49                  
 [5] ggplot2_3.5.1               remotes_2.5.0               processx_3.8.4              Biobase_2.64.0             
 [9] lattice_0.22-5              callr_3.7.6                 vctrs_0.6.5                 tools_4.4.1                
[13] ps_1.8.1                    bitops_1.0-9                generics_0.1.3              curl_6.0.1                 
[17] parallel_4.4.1              tibble_3.2.1                pkgconfig_2.0.3             Matrix_1.6-5               
[21] pheatmap_1.0.12             RColorBrewer_1.1-3          desc_1.4.3                  lifecycle_1.0.4            
[25] GenomeInfoDbData_1.2.12     compiler_4.4.1              Rsamtools_2.20.0            munsell_0.5.1              
[29] codetools_0.2-19            htmltools_0.5.8.1           RCurl_1.98-1.16             yaml_2.3.10                
[33] pillar_1.10.0               crayon_1.5.3                BiocParallel_1.38.0         DelayedArray_0.30.1        
[37] abind_1.4-8                 network_1.19.0              tidyselect_1.2.1            digest_0.6.37              
[41] dplyr_1.1.4                 restfulr_0.0.15             fastmap_1.2.0               grid_4.4.1                 
[45] SparseArray_1.4.8           colorspace_2.1-1            cli_3.6.3                   magrittr_2.0.3             
[49] S4Arrays_1.4.1              XML_3.99-0.17               pkgbuild_1.4.5              UCSC.utils_1.0.0           
[53] scales_1.3.0                ggnetwork_0.5.13            rmarkdown_2.29              httr_1.4.7                 
[57] matrixStats_1.4.1           igraph_2.1.2                coda_0.19-4.1               evaluate_1.0.1             
[61] knitr_1.49                  BiocIO_1.14.0               GenomicRanges_1.56.2        rtracklayer_1.64.0         
[65] rlang_1.1.4                 Rcpp_1.0.13-1               glue_1.8.0                  intergraph_2.0-4           
[69] rstudioapi_0.17.1           jsonlite_1.8.9              R6_2.5.1                    statnet.common_4.10.0      
[73] MatrixGenerics_1.16.0       GenomicAlignments_1.40.0    zlibbioc_1.50.0            
> 
```

Best!

**Comment by almeidasilvaf** [comment]
Hi, @WWz33 

Thank you for writing a detailed and reproducible description.

Now I see where the issue is: in the first analysis, which returns 0 collinear gene pairs, you're using a toy data set in `extdata/` that contains a very small subset of the data available in objects `proteomes` and `annotation`. These FASTA and GFF files in `extdata` serve only to demonstrate how to read data from files. If you pay close attention, you will see that you're not actually running the code in the vignette, that's why you cannot reproduce it.

In summary, the following code loads a subset of the data with only 100 genes (see the length of the `XStringSet` objects). This is what you're doing:

```r
# Read subset of the sequences (n = 100, toy data set)
fasta_dir <- system.file("extdata", "sequences", package = "syntenet")
aastringsetlist <- fasta2AAStringSetlist(fasta_dir)

# Read subset of the annotation (toy data set)
gff_dir <- system.file("extdata", "annotation", package = "syntenet")
grangeslist <- gff2GRangesList(gff_dir)
```

You should instead have used the example objects `proteomes` and `annotation`, which contain the entire genome and annotation, as follows:

```r
data(proteomes)
data(annotation)
```

You can verify that `aastringsetlist` and `proteomes` have different number of sequences with:

```r
lengths(proteomes)
lengths(aastringsetlist)
```

Thus, you were running `interspecies_synteny()` with a subset of the genome. Running it with all (protein-coding) genes works as expected.


All the best,
Fabricio
